// All 58 Wilayas of Algeria
export const ALGERIAN_WILAYAS = [
    "Adrar", "Chlef", "Laghouat", "Oum El Bouaghi", "Batna", "Béjaïa", "Biskra", "Béchar",
    "Blida", "Bouira", "Tamanrasset", "Tébessa", "Tlemcen", "Tiaret", "Tizi Ouzou", "Algiers",
    "Djelfa", "Jijel", "Sétif", "Saïda", "Skikda", "Sidi Bel Abbès", "Annaba", "Guelma",
    "Constantine", "Médéa", "Mostaganem", "M'Sila", "Mascara", "Ouargla", "Oran", "El Bayadh",
    "Illizi", "Bordj Bou Arréridj", "Boumerdès", "El Tarf", "Tindouf", "Tissemsilt", "El Oued",
    "Khenchela", "Souk Ahras", "Tipaza", "Mila", "Aïn Defla", "Naâma", "Aïn Témouchent",
    "Ghardaïa", "Relizane", "Timimoun", "Bordj Badji Mokhtar", "Ouled Djellal", "Béni Abbès",
    "In Salah", "In Guezzam", "Touggourt", "Djanet", "El M'Ghair", "El Menia"
  ];
  
  // Major Algerian Universities (public and notable private)
  export const ALGERIAN_UNIVERSITIES = [
    "University of Algiers 1 – Benyoucef Benkhedda",
    "University of Algiers 2 – Abou El Kacem Saâdallah",
    "University of Algiers 3 – Ibrahim Sultan",
    "University of Science and Technology Houari Boumediene (USTHB)",
    "University of Blida 1 – Saad Dahlab",
    "University of Blida 2 – Lounici Ali",
    "University of Bouira – Akli Mohand Oulhadj",
    "University of Tizi Ouzou – Mouloud Mammeri",
    "University of Béjaïa – Abderrahmane Mira",
    "University of Sétif 1 – Ferhat Abbas",
    "University of Sétif 2 – Mohamed Boudiaf",
    "University of Constantine 1 – Mentouri Brothers",
    "University of Constantine 2 – Abdelhamid Mehri",
    "University of Constantine 3 – Salah Boubnider",
    "University of Annaba – Badji Mokhtar",
    "University of Oran 1 – Ahmed Ben Bella",
    "University of Oran 2 – Mohamed Ben Ahmed",
    "University of Science and Technology of Oran – Mohamed Boudiaf (USTO)",
    "University of Tlemcen – Abou Bekr Belkaïd",
    "University of Tiaret – Ibn Khaldoun",
    "University of Chief – Hassiba Ben Bouali",
    "University of Laghouat – Amar Telidji",
    "University of Biskra – Mohamed Khider",
    "University of Batna 1 – Hadj Lakhdar",
    "University of Batna 2 – Mustafa Ben Boulaid",
    "University of Jijel – Mohammed Seddik Benyahia",
    "University of M'Sila – Mohamed Boudiaf",
    "University of Djelfa – Ziane Achour",
    "University of Médéa – Yahia Fares",
    "University of Mostaganem – Abdelhamid Ibn Badis",
    "University of Mascara – Mustapha Stambouli",
    "University of Ouargla – Kasdi Merbah",
    "University of El Oued – Mohamed El Bachir El Ibrahimi",
    "University of Ghardaïa",
    "University of El Bayadh",
    "University of Illizi – Ammi Saïd",
    "University of Tébessa – Larbi Ben M'Hidi",
    "University of Souk Ahras – Mohamed Chérif Messaadia",
    "University of Khenchela – Abbas Laghrour",
    "University of Saïda – Tahar Moulay",
    "University of Tissemsilt – Ahmed Ben Yahia",
    "University of Tipaza – Mouloud Mammeri (Centre)",
    "University of Boumerdès – M'Hamed Bougara (UMBB)",
    "University of Relizane – Ahmed Zabana",
    "University of Aïn Témouchent – Belhadj Bouchaib",
    "University of Aïn Defla – Djillali Liabes (Tissemsilt)",
    "University of Skikda – 20 Août 1955",
    "University of Guelma – 8 Mai 1945",
    "University of Mila – Abdelhafid Boussouf",
    "University of Naâma",
    "University of Tamanrasset – Ahmed Baba",
    "École Nationale Polytechnique (ENP)",
    "École Nationale Supérieure d'Informatique (ESI)",
    "École Nationale Supérieure de Sciences Politiques (ENSSP)",
    "École Nationale Supérieure de Management (ENSM)",
    "École Nationale Supérieure de Biotechnologie (ENSB)",
    "École Nationale Supérieure de Mathématiques (ENSM)",
    "École Nationale Supérieure de Vétérinaire (ENSV)",
    "École Nationale Supérieure des Technologies Avancées (ENSTA)",
    "École Supérieure d'Enseignement Technologique d'Oran (ESET)",
    "École Supérieure de Commerce (ESC)",
    "École Supérieure de Banque (ESB)",
    "École Supérieure de Gestion et d'Économie (ESGE)",
    "Centre Universitaire de Barika",
    "Centre Universitaire de Ksar Chellala",
    "Centre Universitaire de Maghnia",
    "Centre Universitaire de Nâama",
    "Centre Universitaire de Tindouf",
    "Centre Universitaire de Tizi-Ouzou (Ouaguenoun)",
    "Centre Universitaire de Yakouren"
  ];