import { StudentProfile } from "@/types/profile.types";

export const STUDENT_STATUS_OPTIONS = [
  { id: "studying", label: "Currently Studying", icon: "GraduationCap" },
  { id: "graduated", label: "Graduated", icon: "Calendar" },
  { id: "self_taught", label: "Self‑Taught", icon: "Sparkles" },
] as const;

export const UNIVERSITY_DEPARTMENTS = [
  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biochemistry",
  "Molecular Biology",
  "Genetics",
  "Microbiology",
  "Biotechnology",
  "Environmental Science",
  "Earth Sciences",
  "Geology",
  "Geography",
  "Civil Engineering",
  "Mechanical Engineering",
  "Electrical Engineering",
  "Electronics",
  "Telecommunications",
  "Chemical Engineering",
  "Industrial Engineering",
  "Petroleum Engineering",
  "Mining Engineering",
  "Metallurgy",
  "Aerospace Engineering",
  "Architecture",
  "Urban Planning",
  "Economics",
  "Management",
  "Commerce",
  "Accounting",
  "Finance",
  "Marketing",
  "Business Administration",
  "Public Administration",
  "Political Science",
  "International Relations",
  "Law",
  "Islamic Law (Charia'a)",
  "Literature",
  "Arabic Language & Literature",
  "English Language & Literature",
  "French Language & Literature",
  "Spanish Language & Literature",
  "German Language & Literature",
  "Translation & Interpreting",
  "History",
  "Archaeology",
  "Philosophy",
  "Sociology",
  "Psychology",
  "Educational Sciences",
  "Physical Education & Sports",
  "Journalism & Mass Communication",
  "Library & Information Science",
  "Fine Arts",
  "Music",
  "Theatre & Cinema",
  "Pharmacy",
  "Medicine",
  "Dentistry",
  "Veterinary Medicine",
  "Nursing",
  "Public Health",
  "Agriculture",
  "Agronomy",
  "Food Science & Technology",
  "Forestry",
  "Viticulture & Enology",
  "Fisheries & Aquaculture",
];

export const COMMON_SPECIALITIES = [
  "Computer Science",
  "Software Engineering",
  "Data Science",
  "Artificial Intelligence",
  "Cybersecurity",
  "Business Administration",
  "Marketing",
  "Finance",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Biotechnology",
  "Medicine",
  "Law",
  "Economics",
];

export const COMMON_DEGREES = [
  "License (LMD)",
  "Master (LMD)",
  "Doctorate",
  'Ingenieur (ING)'
];

export const EDUCATION_LEVELS = [
  { value: "bachelor", label: "Bachelor's" },
  { value: "master", label: "Master's" },
  { value: "phd", label: "PhD" },
  { value: "bootcamp", label: "Bootcamp" },
];

export const REQUIRED_STUDENT_FIELDS: (keyof StudentProfile)[] = [
  "first_name",
  "last_name",
  "email",
  "degree_level",
  "university_name",
  "speciality",
  "wilaya",
  "academic_year",
  "speciality_type",
  "student_id"
];