export const UNIVERSITY_DEPARTMENTS = [
    "Computer Science",
    "Software Engineering",
    "Information Technology",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Biochemistry",
    "Molecular Biology",
    "Genetics",
    "Microbiology",
    "Biotechnology",
    "Environmental Science",
    "Earth Sciences",
    "Geology",
    "Geography",
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Electronics",
    "Telecommunications",
    "Chemical Engineering",
    "Industrial Engineering",
    "Petroleum Engineering",
    "Mining Engineering",
    "Metallurgy",
    "Aerospace Engineering",
    "Architecture",
    "Urban Planning",
    "Economics",
    "Management",
    "Commerce",
    "Accounting",
    "Finance",
    "Marketing",
    "Business Administration",
    "Public Administration",
    "Political Science",
    "International Relations",
    "Law",
    "Islamic Law (Charia'a)",
    "Literature",
    "Arabic Language & Literature",
    "English Language & Literature",
    "French Language & Literature",
    "Spanish Language & Literature",
    "German Language & Literature",
    "Translation & Interpreting",
    "History",
    "Archaeology",
    "Philosophy",
    "Sociology",
    "Psychology",
    "Educational Sciences",
    "Physical Education & Sports",
    "Journalism & Mass Communication",
    "Library & Information Science",
    "Fine Arts",
    "Music",
    "Theatre & Cinema",
    "Pharmacy",
    "Medicine",
    "Dentistry",
    "Veterinary Medicine",
    "Nursing",
    "Public Health",
    "Agriculture",
    "Agronomy",
    "Food Science & Technology",
    "Forestry",
    "Viticulture & Enology",
    "Fisheries & Aquaculture",
  ];
  
  export const ACADEMIC_POSITIONS = [
    "Rector / President",
    "Vice-Rector for Academic Affairs",
    "Vice-Rector for Research",
    "Vice-Rector for External Relations",
    "Dean of Faculty",
    "Vice-Dean",
    "Head of Department",
    "Deputy Head of Department",
    "Professor",
    "Associate Professor",
    "Assistant Professor",
    "Senior Lecturer",
    "Lecturer",
    "Assistant Lecturer",
    "Researcher",
    "Senior Researcher",
    "Lab Director",
    "Institute Director",
    "Research Centre Director",
    "Chief of Service",
    "Administrative Director",
    "Finance Director",
    "HR Director",
    "Student Affairs Director",
    "Registrar",
    "Quality Assurance Manager",
    "International Relations Officer",
    "Academic Advisor",
    "Project Manager",
    "IT Director",
  ];